#' ---
#' title: "Engineer Features"
#' author: "Kevin Lu"
#' output: 
#'   html_document: 
#'     toc: true 
#'     toc_float: true
#'     number_sections: false
#' ---

#' # 1. Source
source("./R/01-load-packages.R")
source("./R/02-scrape-bitcoin-data.R")
source("./R/03-scrape-google-data.R")
source("./R/04-scrape-other-data.R")

#' # 2. Clean Bitcoin Price
#' Data errors are cleaned by using last observation carried forward. 
print("Engineering features.")
bitcoin_price[bitcoin_price == 0] <- NA
bitcoin_price <- bitcoin_price %>% 
  map_df(na.locf)

#' # 3. Define Target
bitcoin_model <- bitcoin_price %>% 
  select(date, close) %>% 
  mutate(future_return = lead(close, 1) / close - 1, 
         future_return_sign = ifelse(future_return > 0, 1, 0), 
         future_return_sign = ifelse(is.na(future_return_sign), 0, future_return_sign))

#' # 4. Bitcoin Price Change
bitcoin_model <- bitcoin_model %>% 
  mutate(close_change_01d = close / lag(close, 1) - 1, 
         close_change_02d = close / lag(close, 2) - 1, 
         close_change_03d = close / lag(close, 3) - 1, 
         close_change_04d = close / lag(close, 4) - 1, 
         close_change_05d = close / lag(close, 5) - 1, 
         close_change_06d = close / lag(close, 6) - 1, 
         close_change_07d = close / lag(close, 7) - 1, 
         close_change_08d = close / lag(close, 8) - 1, 
         close_change_09d = close / lag(close, 9) - 1, 
         close_change_10d = close / lag(close, 10) - 1, 
         close_change_11d = close / lag(close, 11) - 1, 
         close_change_12d = close / lag(close, 12) - 1, 
         close_change_13d = close / lag(close, 13) - 1, 
         close_change_14d = close / lag(close, 14) - 1, 
         close_change_15d = close / lag(close, 15) - 1, 
         close_change_16d = close / lag(close, 16) - 1, 
         close_change_17d = close / lag(close, 17) - 1, 
         close_change_18d = close / lag(close, 18) - 1, 
         close_change_19d = close / lag(close, 19) - 1, 
         close_change_20d = close / lag(close, 20) - 1, 
         close_change_21d = close / lag(close, 21) - 1, 
         close_change_22d = close / lag(close, 22) - 1, 
         close_change_23d = close / lag(close, 23) - 1, 
         close_change_24d = close / lag(close, 24) - 1, 
         close_change_25d = close / lag(close, 25) - 1, 
         close_change_26d = close / lag(close, 26) - 1, 
         close_change_27d = close / lag(close, 27) - 1, 
         close_change_28d = close / lag(close, 28) - 1, 
         close_change_29d = close / lag(close, 29) - 1, 
         close_change_30d = close / lag(close, 30) - 1, 
         close_change_31d = close / lag(close, 31) - 1, 
         close_change_32d = close / lag(close, 32) - 1, 
         close_change_33d = close / lag(close, 33) - 1, 
         close_change_34d = close / lag(close, 34) - 1, 
         close_change_35d = close / lag(close, 35) - 1, 
         close_change_36d = close / lag(close, 36) - 1, 
         close_change_37d = close / lag(close, 37) - 1, 
         close_change_38d = close / lag(close, 38) - 1, 
         close_change_39d = close / lag(close, 39) - 1, 
         close_change_40d = close / lag(close, 40) - 1, 
         close_change_41d = close / lag(close, 41) - 1, 
         close_change_42d = close / lag(close, 42) - 1, 
         close_change_43d = close / lag(close, 43) - 1, 
         close_change_44d = close / lag(close, 44) - 1, 
         close_change_45d = close / lag(close, 45) - 1, 
         close_change_46d = close / lag(close, 46) - 1, 
         close_change_47d = close / lag(close, 47) - 1, 
         close_change_48d = close / lag(close, 48) - 1, 
         close_change_49d = close / lag(close, 49) - 1, 
         close_change_50d = close / lag(close, 50) - 1, 
         close_change_51d = close / lag(close, 51) - 1, 
         close_change_52d = close / lag(close, 52) - 1, 
         close_change_53d = close / lag(close, 53) - 1, 
         close_change_54d = close / lag(close, 54) - 1, 
         close_change_55d = close / lag(close, 55) - 1, 
         close_change_56d = close / lag(close, 56) - 1, 
         close_change_57d = close / lag(close, 57) - 1, 
         close_change_58d = close / lag(close, 58) - 1, 
         close_change_59d = close / lag(close, 59) - 1, 
         close_change_60d = close / lag(close, 60) - 1, 
         close_change_61d = close / lag(close, 61) - 1, 
         close_change_62d = close / lag(close, 62) - 1, 
         close_change_63d = close / lag(close, 63) - 1, 
         close_change_64d = close / lag(close, 64) - 1, 
         close_change_65d = close / lag(close, 65) - 1, 
         close_change_66d = close / lag(close, 66) - 1, 
         close_change_67d = close / lag(close, 67) - 1, 
         close_change_68d = close / lag(close, 68) - 1, 
         close_change_69d = close / lag(close, 69) - 1, 
         close_change_70d = close / lag(close, 70) - 1, 
         close_change_71d = close / lag(close, 71) - 1, 
         close_change_72d = close / lag(close, 72) - 1, 
         close_change_73d = close / lag(close, 73) - 1, 
         close_change_74d = close / lag(close, 74) - 1, 
         close_change_75d = close / lag(close, 75) - 1, 
         close_change_76d = close / lag(close, 76) - 1, 
         close_change_77d = close / lag(close, 77) - 1, 
         close_change_78d = close / lag(close, 78) - 1, 
         close_change_79d = close / lag(close, 79) - 1, 
         close_change_80d = close / lag(close, 80) - 1, 
         close_change_81d = close / lag(close, 81) - 1, 
         close_change_82d = close / lag(close, 82) - 1, 
         close_change_83d = close / lag(close, 83) - 1, 
         close_change_84d = close / lag(close, 84) - 1, 
         close_change_85d = close / lag(close, 85) - 1, 
         close_change_86d = close / lag(close, 86) - 1, 
         close_change_87d = close / lag(close, 87) - 1, 
         close_change_88d = close / lag(close, 88) - 1, 
         close_change_89d = close / lag(close, 89) - 1, 
         close_change_90d = close / lag(close, 90) - 1)

#' # 5. Bitcoin Drawdown
bitcoin_model <- bitcoin_model %>% 
  mutate(close_drawdown = -1 * (1 - close / cummax(close)))

#' # 6. Rolling Daily Return Volatility
bitcoin_model <- bitcoin_model %>% 
  mutate(close_sd_01d = 0, 
         close_sd_02d = roll_sdr(close_change_01d, 2, fill = NA), 
         close_sd_03d = roll_sdr(close_change_01d, 3, fill = NA), 
         close_sd_04d = roll_sdr(close_change_01d, 4, fill = NA), 
         close_sd_05d = roll_sdr(close_change_01d, 5, fill = NA), 
         close_sd_06d = roll_sdr(close_change_01d, 6, fill = NA), 
         close_sd_07d = roll_sdr(close_change_01d, 7, fill = NA), 
         close_sd_08d = roll_sdr(close_change_01d, 8, fill = NA), 
         close_sd_09d = roll_sdr(close_change_01d, 9, fill = NA), 
         close_sd_10d = roll_sdr(close_change_01d, 10, fill = NA), 
         close_sd_11d = roll_sdr(close_change_01d, 11, fill = NA), 
         close_sd_12d = roll_sdr(close_change_01d, 12, fill = NA), 
         close_sd_13d = roll_sdr(close_change_01d, 13, fill = NA), 
         close_sd_14d = roll_sdr(close_change_01d, 14, fill = NA), 
         close_sd_15d = roll_sdr(close_change_01d, 15, fill = NA), 
         close_sd_16d = roll_sdr(close_change_01d, 16, fill = NA), 
         close_sd_17d = roll_sdr(close_change_01d, 17, fill = NA), 
         close_sd_18d = roll_sdr(close_change_01d, 18, fill = NA), 
         close_sd_19d = roll_sdr(close_change_01d, 19, fill = NA), 
         close_sd_20d = roll_sdr(close_change_01d, 20, fill = NA), 
         close_sd_21d = roll_sdr(close_change_01d, 21, fill = NA), 
         close_sd_22d = roll_sdr(close_change_01d, 22, fill = NA), 
         close_sd_23d = roll_sdr(close_change_01d, 23, fill = NA), 
         close_sd_24d = roll_sdr(close_change_01d, 24, fill = NA), 
         close_sd_25d = roll_sdr(close_change_01d, 25, fill = NA), 
         close_sd_26d = roll_sdr(close_change_01d, 26, fill = NA), 
         close_sd_27d = roll_sdr(close_change_01d, 27, fill = NA), 
         close_sd_28d = roll_sdr(close_change_01d, 28, fill = NA), 
         close_sd_29d = roll_sdr(close_change_01d, 29, fill = NA), 
         close_sd_30d = roll_sdr(close_change_01d, 30, fill = NA), 
         close_sd_31d = roll_sdr(close_change_01d, 31, fill = NA), 
         close_sd_32d = roll_sdr(close_change_01d, 32, fill = NA), 
         close_sd_33d = roll_sdr(close_change_01d, 33, fill = NA), 
         close_sd_34d = roll_sdr(close_change_01d, 34, fill = NA), 
         close_sd_35d = roll_sdr(close_change_01d, 35, fill = NA), 
         close_sd_36d = roll_sdr(close_change_01d, 36, fill = NA), 
         close_sd_37d = roll_sdr(close_change_01d, 37, fill = NA), 
         close_sd_38d = roll_sdr(close_change_01d, 38, fill = NA), 
         close_sd_39d = roll_sdr(close_change_01d, 39, fill = NA), 
         close_sd_40d = roll_sdr(close_change_01d, 40, fill = NA), 
         close_sd_41d = roll_sdr(close_change_01d, 41, fill = NA), 
         close_sd_42d = roll_sdr(close_change_01d, 42, fill = NA), 
         close_sd_43d = roll_sdr(close_change_01d, 43, fill = NA), 
         close_sd_44d = roll_sdr(close_change_01d, 44, fill = NA), 
         close_sd_45d = roll_sdr(close_change_01d, 45, fill = NA), 
         close_sd_46d = roll_sdr(close_change_01d, 46, fill = NA), 
         close_sd_47d = roll_sdr(close_change_01d, 47, fill = NA), 
         close_sd_48d = roll_sdr(close_change_01d, 48, fill = NA), 
         close_sd_49d = roll_sdr(close_change_01d, 49, fill = NA), 
         close_sd_50d = roll_sdr(close_change_01d, 50, fill = NA), 
         close_sd_51d = roll_sdr(close_change_01d, 51, fill = NA), 
         close_sd_52d = roll_sdr(close_change_01d, 52, fill = NA), 
         close_sd_53d = roll_sdr(close_change_01d, 53, fill = NA), 
         close_sd_54d = roll_sdr(close_change_01d, 54, fill = NA), 
         close_sd_55d = roll_sdr(close_change_01d, 55, fill = NA), 
         close_sd_56d = roll_sdr(close_change_01d, 56, fill = NA), 
         close_sd_57d = roll_sdr(close_change_01d, 57, fill = NA), 
         close_sd_58d = roll_sdr(close_change_01d, 58, fill = NA), 
         close_sd_59d = roll_sdr(close_change_01d, 59, fill = NA), 
         close_sd_60d = roll_sdr(close_change_01d, 60, fill = NA), 
         close_sd_61d = roll_sdr(close_change_01d, 61, fill = NA), 
         close_sd_62d = roll_sdr(close_change_01d, 62, fill = NA), 
         close_sd_63d = roll_sdr(close_change_01d, 63, fill = NA), 
         close_sd_64d = roll_sdr(close_change_01d, 64, fill = NA), 
         close_sd_65d = roll_sdr(close_change_01d, 65, fill = NA), 
         close_sd_66d = roll_sdr(close_change_01d, 66, fill = NA), 
         close_sd_67d = roll_sdr(close_change_01d, 67, fill = NA), 
         close_sd_68d = roll_sdr(close_change_01d, 68, fill = NA), 
         close_sd_69d = roll_sdr(close_change_01d, 69, fill = NA), 
         close_sd_70d = roll_sdr(close_change_01d, 70, fill = NA), 
         close_sd_71d = roll_sdr(close_change_01d, 71, fill = NA), 
         close_sd_72d = roll_sdr(close_change_01d, 72, fill = NA), 
         close_sd_73d = roll_sdr(close_change_01d, 73, fill = NA), 
         close_sd_74d = roll_sdr(close_change_01d, 74, fill = NA), 
         close_sd_75d = roll_sdr(close_change_01d, 75, fill = NA), 
         close_sd_76d = roll_sdr(close_change_01d, 76, fill = NA), 
         close_sd_77d = roll_sdr(close_change_01d, 77, fill = NA), 
         close_sd_78d = roll_sdr(close_change_01d, 78, fill = NA), 
         close_sd_79d = roll_sdr(close_change_01d, 79, fill = NA), 
         close_sd_80d = roll_sdr(close_change_01d, 80, fill = NA), 
         close_sd_81d = roll_sdr(close_change_01d, 81, fill = NA), 
         close_sd_82d = roll_sdr(close_change_01d, 82, fill = NA), 
         close_sd_83d = roll_sdr(close_change_01d, 83, fill = NA), 
         close_sd_84d = roll_sdr(close_change_01d, 84, fill = NA), 
         close_sd_85d = roll_sdr(close_change_01d, 85, fill = NA), 
         close_sd_86d = roll_sdr(close_change_01d, 86, fill = NA), 
         close_sd_87d = roll_sdr(close_change_01d, 87, fill = NA), 
         close_sd_88d = roll_sdr(close_change_01d, 88, fill = NA), 
         close_sd_89d = roll_sdr(close_change_01d, 89, fill = NA), 
         close_sd_90d = roll_sdr(close_change_01d, 90, fill = NA))

#' # 7. Number of Positive Days
bitcoin_model <- bitcoin_model %>% 
  mutate(close_positive = ifelse(close_change_01d > 0, 1, 0), 
         close_negative = ifelse(close_change_01d <= 0, 1, 0), 
         close_positive_01d = roll_sumr(close_positive, 1, fill = NA), 
         close_positive_02d = roll_sumr(close_positive, 2, fill = NA), 
         close_positive_03d = roll_sumr(close_positive, 3, fill = NA), 
         close_positive_04d = roll_sumr(close_positive, 4, fill = NA), 
         close_positive_05d = roll_sumr(close_positive, 5, fill = NA), 
         close_positive_06d = roll_sumr(close_positive, 6, fill = NA), 
         close_positive_07d = roll_sumr(close_positive, 7, fill = NA), 
         close_positive_08d = roll_sumr(close_positive, 8, fill = NA), 
         close_positive_09d = roll_sumr(close_positive, 9, fill = NA), 
         close_positive_10d = roll_sumr(close_positive, 10, fill = NA), 
         close_positive_11d = roll_sumr(close_positive, 11, fill = NA), 
         close_positive_12d = roll_sumr(close_positive, 12, fill = NA), 
         close_positive_13d = roll_sumr(close_positive, 13, fill = NA), 
         close_positive_14d = roll_sumr(close_positive, 14, fill = NA), 
         close_positive_15d = roll_sumr(close_positive, 15, fill = NA), 
         close_positive_16d = roll_sumr(close_positive, 16, fill = NA), 
         close_positive_17d = roll_sumr(close_positive, 17, fill = NA), 
         close_positive_18d = roll_sumr(close_positive, 18, fill = NA), 
         close_positive_19d = roll_sumr(close_positive, 19, fill = NA), 
         close_positive_20d = roll_sumr(close_positive, 20, fill = NA), 
         close_positive_21d = roll_sumr(close_positive, 21, fill = NA), 
         close_positive_22d = roll_sumr(close_positive, 22, fill = NA), 
         close_positive_23d = roll_sumr(close_positive, 23, fill = NA), 
         close_positive_24d = roll_sumr(close_positive, 24, fill = NA), 
         close_positive_25d = roll_sumr(close_positive, 25, fill = NA), 
         close_positive_26d = roll_sumr(close_positive, 26, fill = NA), 
         close_positive_27d = roll_sumr(close_positive, 27, fill = NA), 
         close_positive_28d = roll_sumr(close_positive, 28, fill = NA), 
         close_positive_29d = roll_sumr(close_positive, 29, fill = NA), 
         close_positive_30d = roll_sumr(close_positive, 30, fill = NA), 
         close_positive_31d = roll_sumr(close_positive, 31, fill = NA), 
         close_positive_32d = roll_sumr(close_positive, 32, fill = NA), 
         close_positive_33d = roll_sumr(close_positive, 33, fill = NA), 
         close_positive_34d = roll_sumr(close_positive, 34, fill = NA), 
         close_positive_35d = roll_sumr(close_positive, 35, fill = NA), 
         close_positive_36d = roll_sumr(close_positive, 36, fill = NA), 
         close_positive_37d = roll_sumr(close_positive, 37, fill = NA), 
         close_positive_38d = roll_sumr(close_positive, 38, fill = NA), 
         close_positive_39d = roll_sumr(close_positive, 39, fill = NA), 
         close_positive_40d = roll_sumr(close_positive, 40, fill = NA), 
         close_positive_41d = roll_sumr(close_positive, 41, fill = NA), 
         close_positive_42d = roll_sumr(close_positive, 42, fill = NA), 
         close_positive_43d = roll_sumr(close_positive, 43, fill = NA), 
         close_positive_44d = roll_sumr(close_positive, 44, fill = NA), 
         close_positive_45d = roll_sumr(close_positive, 45, fill = NA), 
         close_positive_46d = roll_sumr(close_positive, 46, fill = NA), 
         close_positive_47d = roll_sumr(close_positive, 47, fill = NA), 
         close_positive_48d = roll_sumr(close_positive, 48, fill = NA), 
         close_positive_49d = roll_sumr(close_positive, 49, fill = NA), 
         close_positive_50d = roll_sumr(close_positive, 50, fill = NA), 
         close_positive_51d = roll_sumr(close_positive, 51, fill = NA), 
         close_positive_52d = roll_sumr(close_positive, 52, fill = NA), 
         close_positive_53d = roll_sumr(close_positive, 53, fill = NA), 
         close_positive_54d = roll_sumr(close_positive, 54, fill = NA), 
         close_positive_55d = roll_sumr(close_positive, 55, fill = NA), 
         close_positive_56d = roll_sumr(close_positive, 56, fill = NA), 
         close_positive_57d = roll_sumr(close_positive, 57, fill = NA), 
         close_positive_58d = roll_sumr(close_positive, 58, fill = NA), 
         close_positive_59d = roll_sumr(close_positive, 59, fill = NA), 
         close_positive_60d = roll_sumr(close_positive, 60, fill = NA), 
         close_positive_61d = roll_sumr(close_positive, 61, fill = NA), 
         close_positive_62d = roll_sumr(close_positive, 62, fill = NA), 
         close_positive_63d = roll_sumr(close_positive, 63, fill = NA), 
         close_positive_64d = roll_sumr(close_positive, 64, fill = NA), 
         close_positive_65d = roll_sumr(close_positive, 65, fill = NA), 
         close_positive_66d = roll_sumr(close_positive, 66, fill = NA), 
         close_positive_67d = roll_sumr(close_positive, 67, fill = NA), 
         close_positive_68d = roll_sumr(close_positive, 68, fill = NA), 
         close_positive_69d = roll_sumr(close_positive, 69, fill = NA), 
         close_positive_70d = roll_sumr(close_positive, 70, fill = NA),
         close_positive_71d = roll_sumr(close_positive, 71, fill = NA), 
         close_positive_72d = roll_sumr(close_positive, 72, fill = NA), 
         close_positive_73d = roll_sumr(close_positive, 73, fill = NA), 
         close_positive_74d = roll_sumr(close_positive, 74, fill = NA), 
         close_positive_75d = roll_sumr(close_positive, 75, fill = NA), 
         close_positive_76d = roll_sumr(close_positive, 76, fill = NA), 
         close_positive_77d = roll_sumr(close_positive, 77, fill = NA), 
         close_positive_78d = roll_sumr(close_positive, 78, fill = NA), 
         close_positive_79d = roll_sumr(close_positive, 79, fill = NA), 
         close_positive_80d = roll_sumr(close_positive, 80, fill = NA), 
         close_positive_81d = roll_sumr(close_positive, 81, fill = NA), 
         close_positive_82d = roll_sumr(close_positive, 82, fill = NA), 
         close_positive_83d = roll_sumr(close_positive, 83, fill = NA), 
         close_positive_84d = roll_sumr(close_positive, 84, fill = NA), 
         close_positive_85d = roll_sumr(close_positive, 85, fill = NA), 
         close_positive_86d = roll_sumr(close_positive, 86, fill = NA), 
         close_positive_87d = roll_sumr(close_positive, 87, fill = NA), 
         close_positive_88d = roll_sumr(close_positive, 88, fill = NA), 
         close_positive_89d = roll_sumr(close_positive, 89, fill = NA), 
         close_positive_90d = roll_sumr(close_positive, 90, fill = NA))

#' # 8. Number of Positive and Negative Days in a Row
bitcoin_model <- bitcoin_model %>% 
  mutate(close_positive_streak = close_positive * unlist(map(rle(close_positive)[["lengths"]], seq_len)), 
         close_negative_streak = close_negative * unlist(map(rle(close_negative)[["lengths"]], seq_len)))

#' # 9. Calculate Google Trends Change
bitcoin_model <- bitcoin_model %>% 
  left_join(bitcoin_google) %>% 
  mutate(hits_daily_01d = hits_daily / lag(hits_daily, 1) - 1, 
         hits_daily_02d = hits_daily / lag(hits_daily, 2) - 1, 
         hits_daily_03d = hits_daily / lag(hits_daily, 3) - 1, 
         hits_daily_04d = hits_daily / lag(hits_daily, 4) - 1, 
         hits_daily_05d = hits_daily / lag(hits_daily, 5) - 1, 
         hits_daily_06d = hits_daily / lag(hits_daily, 6) - 1, 
         hits_daily_07d = hits_daily / lag(hits_daily, 7) - 1, 
         hits_daily_08d = hits_daily / lag(hits_daily, 8) - 1, 
         hits_daily_09d = hits_daily / lag(hits_daily, 9) - 1, 
         hits_daily_10d = hits_daily / lag(hits_daily, 10) - 1, 
         hits_daily_11d = hits_daily / lag(hits_daily, 11) - 1, 
         hits_daily_12d = hits_daily / lag(hits_daily, 12) - 1, 
         hits_daily_13d = hits_daily / lag(hits_daily, 13) - 1, 
         hits_daily_14d = hits_daily / lag(hits_daily, 14) - 1, 
         hits_daily_15d = hits_daily / lag(hits_daily, 15) - 1, 
         hits_daily_16d = hits_daily / lag(hits_daily, 16) - 1, 
         hits_daily_17d = hits_daily / lag(hits_daily, 17) - 1, 
         hits_daily_18d = hits_daily / lag(hits_daily, 18) - 1, 
         hits_daily_19d = hits_daily / lag(hits_daily, 19) - 1, 
         hits_daily_20d = hits_daily / lag(hits_daily, 20) - 1, 
         hits_daily_21d = hits_daily / lag(hits_daily, 21) - 1, 
         hits_daily_22d = hits_daily / lag(hits_daily, 22) - 1, 
         hits_daily_23d = hits_daily / lag(hits_daily, 23) - 1, 
         hits_daily_24d = hits_daily / lag(hits_daily, 24) - 1, 
         hits_daily_25d = hits_daily / lag(hits_daily, 25) - 1, 
         hits_daily_26d = hits_daily / lag(hits_daily, 26) - 1, 
         hits_daily_27d = hits_daily / lag(hits_daily, 27) - 1, 
         hits_daily_28d = hits_daily / lag(hits_daily, 28) - 1, 
         hits_daily_29d = hits_daily / lag(hits_daily, 29) - 1, 
         hits_daily_30d = hits_daily / lag(hits_daily, 30) - 1)

#' # 10. Smoothed Google Trends
bitcoin_model <- bitcoin_model %>% 
  mutate(hits_daily_sma_01d = roll_meanr(hits_daily, 1, fill = NA), 
         hits_daily_sma_02d = roll_meanr(hits_daily, 2, fill = NA), 
         hits_daily_sma_03d = roll_meanr(hits_daily, 3, fill = NA), 
         hits_daily_sma_04d = roll_meanr(hits_daily, 4, fill = NA), 
         hits_daily_sma_05d = roll_meanr(hits_daily, 5, fill = NA), 
         hits_daily_sma_06d = roll_meanr(hits_daily, 6, fill = NA), 
         hits_daily_sma_07d = roll_meanr(hits_daily, 7, fill = NA), 
         hits_daily_sma_08d = roll_meanr(hits_daily, 8, fill = NA), 
         hits_daily_sma_09d = roll_meanr(hits_daily, 9, fill = NA), 
         hits_daily_sma_10d = roll_meanr(hits_daily, 10, fill = NA))

#' # 11. Calculate Google Trends Drawdown
bitcoin_model <- bitcoin_model %>%
  mutate(hits_daily_drawdown = -1 * (1 - hits_daily / cummax(hits_daily)))

#' # 12. VIX
bitcoin_model <- bitcoin_model %>% 
  left_join(vix)

#' # 13. Split Into Train Set
train <- bitcoin_model


